version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}

    image: zfitspa:latest
    restart: unless-stopped

    hostname: app

    expose:
      - "3002"

    networks:
      dokploy-network:
        aliases:
          - app

    environment:
      NODE_ENV: production

      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}

      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SECURE: ${EMAIL_SECURE}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_TO: ${EMAIL_TO}

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3002 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  dokploy-network:
    external: true